default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: instagram_development
  
test:
  <<: *default
  database: instagram_test
  
production:
  <<: *default
  database: instagram_production
  username: instagram
  password: <%= ENV['INSTAGRAM_DATABASE_PASSWORD'] %>
